name: xray
channels:
  - conda-forge
  - defaults
  - intel
dependencies:
  - mlflow
  - pytorch
  - pandas
  - torchvision
  - tqdm
  - matplotlib
  - scikit-learn
  - paramiko
  - imgaug
  - plotly
  - pip
  - pip:
      - opencv-python==4.1.2.30
      - torchgan
      - imutils